### ISSUE TITLE
0.101 marked as UNAUTHORIZED on MetaCPAN

### ISSUE THREAD

**Issue by eserte** [briandfoy/pod-pseudopod-docbook#2]
See https://metacpan.org/release/BDFOY/Pod-PseudoPod-DocBook-0.101

This means that from MetaCPAN point of view there's no officially released version of this module, and a search for this module or trying the direct link https://metacpan.org/release/Pod-PseudoPod-DocBook fails currently.

**Comment by briandfoy** [comment]
I'm not going to distribute this module on CPAN any longer. It's something that's specialized to me writing O'Reilly books and I'm never going to spend the time to make it do more than that. Thanks for noticing this though.
